<?php

namespace App\Models;

use App\Events\PostCreated;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Post extends Model
{
    use HasFactory;

    protected $fillable = [
        'original_url', 'shorten_url'
    ];

    public function getRouteKeyName(){
        return "shorten_url";
    }

    public function getCreatedAtAttribute($value){
        return Carbon::parse($value)->diffForHumans();
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($url){
            $url->shorten_url = Str::random();
        });
    }

    /*protected $dispatchesEvents = [
      'created' => PostCreated::class
    ];*/
}
